version: "3"
services:

  # Resolving container hostnames from host machine
  # CAUTION: could affect host machine networking
#  dns-social-network:
#    image: defreitas/dns-proxy-server
#    volumes:
#      - /opt/dns-proxy-server/conf:/app/conf
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /etc/resolv.conf:/etc/resolv.conf

  test-nsfw-keras:
    image: yz2297/social-network-media-filter-debug
    container_name: social-network-media-filter-debug
    ports:
      - 40000:40000
    restart: always